### ISSUE TITLE
感谢分享，用您的EFI配置成功安装！

### ISSUE THREAD

**Issue by JanzTam** [eamonzzz/EFI-Z390-TOMAHAWK-RX590#1]
我的配置：
主板：Z390 Aorus Pro Wi-Fi
显卡：蓝宝石RX590
CPU：i7 9700K

有些问题请教一下。
1. 主板自带的网卡用不了的么？指的是技嘉Z390 Aorus Pro Wi-Fi
2. 您用的是无驱动网卡吗？直接插上就能用么？

**Comment by eamonzzz** [comment]
> 我的配置：
> 主板：Z390 Aorus Pro Wi-Fi
> 显卡：蓝宝石RX590
> CPU：i7 9700K
> 
> 有些问题请教一下。
> 
> 1. 主板自带的网卡用不了的么？指的是技嘉Z390 Aorus Pro Wi-Fi
> 2. 您用的是无驱动网卡吗？直接插上就能用么？

我没搞自带的无线网卡。使用的博通免驱的网卡

**Comment by JanzTam** [comment]
OK！明白了！再次感谢哈～

**Comment by JanzTam** [comment]
怎么从 Clover 迁移到 OC 呢？能直接通过U盘安装盘来弄么
